FROM python:3.12-slim

WORKDIR /app
COPY app.py .
COPY fetch_wrapper.py .
COPY requirements.txt .

RUN apt-get update && apt-get install -y ca-certificates
RUN pip install -r requirements.txt
RUN pip install gunicorn


ENV PORT 8000
EXPOSE 8000

ENTRYPOINT ["sh", "-c", "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 & python fetch_wrapper.py"]
